---
name: Hello World nummer 1

# Workflow wird bei jedem Push ausgeführt
on: push

jobs:
  hello: # nummer 2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository # nummer 3
        uses: actions/checkout@v4

      - name: Print Hello World # nummer 4
        run: echo "Hello, World from ${CWD} as ${USER}!"

      - name: Orientierung gewinnen
        run: ls -l && find

      - name: Welche Dateien wurden geändert?
        run: cat $GITHUB_EVENT_PATH

      - name: Vorher noch jq installieren
        run: sudo apt install jq

      - name: Geänderte Dateien extrahieren und anzeigen
        run: jq '.commits[].modified + .commits[].added + .commits[].removed' $GITHUB_EVENT_PATH

      - name: Send HTTP POST Request (JSON)
        run: |
          curl -X POST "http://mqtt.gypriot.de/v1/action" \
               -H "Content-Type: application/json" \
               -d '{"status":"one"}'

      - name: Send HTTP POST Request (JSON)
        run: curl -X POST 'http://mqtt.gypriot.de/v1/action' -H 'Content-Type:application/json' -d '{"status":"two"}'

      - name: Send HTTP POST Request (JSON)
        run: curl -X POST "http://mqtt.gypriot.de/v1/action" -H "Content-Type:application/json" -d '{"status":"three"}'
